# https://github.com/pages-themes/cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: [egate Trade - Your Equity Gate]
description: [Online Portfolio Management System]
show_downloads: false
